
---
- name: "Common tasks for all hosts"
  hosts: all
  become: yes
  roles:
    - common

- name: "Configure web servers"
  hosts: webservers
  become: yes
  roles:
    - webserver

- name: "Configure database servers"
  hosts: dbservers
  become: yes
  roles:
    - database
